### PR TITLE
Final Helix implementation

### PR DESCRIPTION
**Pull request by Ignoble61**
I appreciate this script is only used by myself and my household, but I feel the final Helix changes may as well be in the official repo for it (and, as a household, I think it's fair to say we find it a very useful script) - obviously understand if it's time to let this script die for everyone but us :)

### CODE REVIEW

**Comment by phil65** [comment]
? Are you Unfledged?

**Comment by Ignoble61** [comment]
Yup, but I've always preferred my secret identity.

**Comment by phil65** [comment]
that´s good news :)
Do you want me to take care of repo-pushing etc?
Feel free to drop me a mail. phil65@kodi.tv

**Comment by Ignoble61** [comment]
I think it's fair to say I have been encouraged to have no great interest in repo pushing or the like - I'm much *much* happier developing scripts/skins for my households usage :) Also hope you will understand, after the unpleasantness that made me leave the active community, if I keep any and all interactions public, rather than e-mail, pm, etc :)

**Comment by phil65** [comment]
All fine for me. Thx that you share some of your "household work" again :)

**Comment by Ignoble61** [comment]
You're very welcome :)

**Comment by phil65** [comment]
addon.xml still refers to your old alias. That´s fine for you?

**Comment by Ignoble61** [comment]
TBH not something I've thought about. And, to be fair, as someone who isn't going to be seen to be active in the community, my initial thought is that it really doesn't matter.

My second thought is that, if I'm going to be actively contributing code (and potentially support via GitHub issues, which I continue to monitor for my scripts to this day), then the alias under which I do makes a difference to those looking for support. Overall, I suspect it doesn't matter for the moment, and I'll update it as and when I have any Isendard updates available, if that seems OK to you.

**Comment by phil65** [comment]
yes, of course fine by me, just thaught I would mention this. Lookin forward to your contributions! :)

**Comment by phil65** [comment]
could you activate issues lists for your add-ons on github?
Couldnt get this add-on to work on first try (using Isengard), just gettin a
20:24:02 T:6084   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://service.smartish.widgets/?type=movies&reload=10
error.  DB file only gets 4kb in size.

**Comment by Ignoble61** [comment]
I've enabled issues.

**Pull request merged**
